In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d  

from matplotlib.colors import ListedColormap

In [3]:
data = pd.read_csv('drag_curves.csv')

data.head()

,v_1,d_1,v_2,d_2,v_3,d_3,v_4,d_4,v_5,d_5
0,4914.59786,51.37169,7494.24199,7.62064,4714.04626,32.85192,805.25623,21.90155,797.39146,15.64419
1,4894.93594,51.32123,7474.58007,7.82249,4706.18149,32.59961,824.91815,21.85108,809.18861,15.39187
2,4875.27402,51.37169,7454.91815,7.97388,4710.11388,32.34730,844.58007,21.85108,824.91815,15.19002
3,4855.61210,51.37169,7435.25623,8.07480,4725.84342,32.09499,864.24199,21.90155,844.58007,15.03864
4,4835.95018,51.37169,7415.59431,8.17573,4745.50534,31.84267,883.90391,21.90155,864.24199,14.88725

In [ ]:
def traj_disp_new(n, data):
    if n==1:
        
        r_speed = (5500, 7800)


    elif n==2:
        r_speed = (4330, 5500)

    elif n==3:
        r_speed = (3400, 4330)

    elif n==4:
        r_speed = (1950, 3400)

    elif n==5:
        r_speed = (300, 1950)
        
    traj_data = data[(data['range'].between(*r_range)) & (data['speed'].between(*r_speed))][['range', 'speed', 'drag', 'entry_phase']]

    traj_vel = traj_data['speed'].to_numpy()
    traj_drag = traj_data['drag'].to_numpy()
    traj_color = traj_data['drag'].to_numpy()

    traj_x = np.array([traj_x_convert_new(n, v, d) for v, d in zip(traj_vel, traj_drag)])
    traj_y = np.array([traj_y_convert_new(n, v) for v in traj_vel])

    trajplot_lines_new(n, [traj_x, traj_y, traj_color])

def trajplot_lines_new(n, data):
    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(12, 7))

    plt_ = ax
    
    img = plt.imread("traj" + str(n) + ".png")
    plt_.imshow(img, aspect='auto', extent=[0, 500, 50, 350])

    
    custom_cmap = plt.cm.get_cmap('viridis', 20)
        
    plt1 = plt_.scatter(
                       data[0],
                       data[1],
        c=data[2], cmap=custom_cmap, s=10)


    major_ticks = np.arange(0, 500, 25)
    
    ax.set_xticks(major_ticks)
    ax.set_yticks(major_ticks)
    
    # And a corresponding grid
    ax.grid(which='both')
    
    plt_.set_xlim([0, 500])
    plt_.set_ylim([50, 350])
    
    cbar = plt.colorbar(plt1)
    
        
def traj_x_convert_new(n, vel, drag):
    
    if n==1:
        return 1221.8492768869419 + 0.06539042505511539 * vel**1 * drag**0 + -211.8206040700076 * vel**0 * drag**1 + -3.665448458782899e-05 * vel**2 * drag**0 + 0.023576901393660615 * vel**1 * drag**1 + 6.12823555795536 * vel**0 * drag**2 + 2.833349485587e-09 * vel**3 * drag**0 + -9.179574484665027e-07 * vel**2 * drag**1 + -0.00026682724201671166 * vel**1 * drag**2 + -0.06810957054774618 * vel**0 * drag**3
    elif n==2:
        return -38.0268152009462 + 0.09906578419425373 * vel**1 * drag**0 + -12.707084859116666 * vel**0 * drag**1 + 1.3305326295037778e-06 * vel**2 * drag**0 + 0.0011766877774739082 * vel**1 * drag**1 + -0.014838331795402771 * vel**0 * drag**2
    elif n==3:
        return -531.1596833649385 + 0.2369508010818678 * vel**1 * drag**0 + -0.7771572651359938 * vel**0 * drag**1 + -2.1586890749936138e-07 * vel**2 * drag**0 + 0.00021100580946806138 * vel**1 * drag**1 + -0.1132059499998106 * vel**0 * drag**2
    elif n==4:
        return -748.4063596835092 + 0.7408869827508833 * vel**1 * drag**0 + -13.833348494044804 * vel**0 * drag**1 + -8.626522934807035e-05 * vel**2 * drag**0 + 2.9372518671475292e-05 * vel**1 * drag**1 + 0.10761028181794845 * vel**0 * drag**2
    elif n==5:
        return -776.3651212085673 + 1.0608120994108508 * vel**1 * drag**0 + -0.0012408627622487007 * vel**0 * drag**1 + -0.000190689080882267 * vel**2 * drag**0 + -0.0018267317853930109 * vel**1 * drag**1 + -0.062043138111733405 * vel**0 * drag**2
        
            
def traj_y_convert_new(n, vel):

    if n==1:
        out = (-0.1187007912 * vel + 966.857 + 32.7)
    elif n==2:
        out = (-0.23731299972 * vel + 1342.6666 + 32.7)
    elif n==3:
        out = (-0.255413394 * vel + 1170 + 32.7)
    elif n==4:
        out = (-0.171587932 * vel + 639 + 32.7)
    elif n==5:
        out = (-0.2568241552 * vel + 565.714 + 32.7)

    return  50 - (out - 350)
    
#traj_bounds= [[0, 500], [50, 350]]